<Demo1>:
    MDLabel:
        id: tela1
        text: 'Screen1'
        halign: "center"
    MDRaisedButton:
        text: "go to screen 2"
        pos_hint: {"center_y": .6, "center_x": .5}
        on_release: root.ids.tela1.text = "bexman"
       

<Demo2>:
    MDLabel:
        text: 'Screen2'
        halign: "center"
    MDRaisedButton:
        text: "go to screen 1"
        pos_hint: {"center_y": .6, "center_x": .5}
        on_release: root.manager.current = "demo1"